In [11]:
# Numpy에 대한 자세한 설명은 https://www.numpy.org/ 

In [3]:
import numpy as np

arr1 = np.arange(15).reshape(3,5)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
# 배열의 형태 출력
arr1.shape

(3, 5)

In [5]:
# 배열 형식 출력
arr1.dtype

dtype('int64')

In [6]:
arr2 = np.array([6, 7, 8])
print(arr2)

[6 7 8]


In [7]:
# 0으로 구성된 배열 생성
arr3 = np.zeros((3,4))
print(arr3)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [10]:
# 배열의 사칙연산 
arr4 = np.array([
    [1,2,3],
    [4,5,6]
], dtype = np.float64)

arr5 = np.array([
    [7,8,9],
    [10,11,12]
], dtype=np.float64)

print('arr4 + arr5 = ')
print(arr4 + arr5, '\n')
print('arr4 - arr5 = ')
print(arr4 - arr5, '\n')
print('arr4 * arr5 = ')
print(arr4 * arr5, '\n')
print('arr4 / arr5 = ')
print(arr4 / arr5, '\n')

arr4 + arr5 = 
[[  8.  10.  12.]
 [ 14.  16.  18.]] 

arr4 - arr5 = 
[[-6. -6. -6.]
 [-6. -6. -6.]] 

arr4 * arr5 = 
[[  7.  16.  27.]
 [ 40.  55.  72.]] 

arr4 / arr5 = 
[[ 0.14285714  0.25        0.33333333]
 [ 0.4         0.45454545  0.5       ]] 

